// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyApp.Infrastructure.Data;

#nullable disable

namespace MyApp.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251107132039_Descruiption added")]
    partial class Descruiptionadded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyApp.Domain.Entities.Device", b =>
                {
                    b.Property<Guid>("DeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("DeviceConfigurationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Host")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Port")
                        .HasColumnType("int");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DeviceId");

                    b.HasIndex("DeviceConfigurationId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("MyApp.Domain.Entities.DeviceConfiguration", b =>
                {
                    b.Property<Guid>("ConfigurationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PollIntervalMs")
                        .HasColumnType("int");

                    b.Property<string>("ProtocolSettingsJson")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ConfigurationId");

                    b.ToTable("DeviceConfigurations");
                });

            modelBuilder.Entity("MyApp.Domain.Entities.DevicePort", b =>
                {
                    b.Property<Guid>("DevicePortId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsHealthy")
                        .HasColumnType("bit");

                    b.Property<int>("PortIndex")
                        .HasColumnType("int");

                    b.Property<Guid>("PortSetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RegisterAddress")
                        .HasColumnType("int");

                    b.Property<int>("RegisterLength")
                        .HasColumnType("int");

                    b.Property<double>("Scale")
                        .HasColumnType("float");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DevicePortId");

                    b.HasIndex("PortSetId");

                    b.HasIndex("DeviceId", "PortIndex");

                    b.ToTable("DevicePorts");
                });

            modelBuilder.Entity("MyApp.Domain.Entities.DevicePortSet", b =>
                {
                    b.Property<Guid>("PortSetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PortSetId");

                    b.HasIndex("DeviceId");

                    b.ToTable("DevicePortSets");
                });

            modelBuilder.Entity("MyApp.Domain.Entities.Device", b =>
                {
                    b.HasOne("MyApp.Domain.Entities.DeviceConfiguration", "DeviceConfiguration")
                        .WithMany()
                        .HasForeignKey("DeviceConfigurationId");

                    b.Navigation("DeviceConfiguration");
                });

            modelBuilder.Entity("MyApp.Domain.Entities.DevicePort", b =>
                {
                    b.HasOne("MyApp.Domain.Entities.DevicePortSet", "PortSet")
                        .WithMany()
                        .HasForeignKey("PortSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PortSet");
                });

            modelBuilder.Entity("MyApp.Domain.Entities.DevicePortSet", b =>
                {
                    b.HasOne("MyApp.Domain.Entities.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });
#pragma warning restore 612, 618
        }
    }
}
